name: Tests

on: 
  push:
    branches:
    - 'main'
    - 'develop'


jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.21.6'

    - name: Install dependencies
      run: go mod download

    - name: Run tests
      run: |
        for dir in $(find . -type d -name "*_test"); do
          echo "Running tests in $dir"
          go test ./$dir/...
        done

    - name: Test Summary
      uses: test-summary/action@v1
      with:
        paths: report.xml            
      if: always()

    # - name: Test
    #   uses: robherley/go-test-action@v0.2.0
    #   with:
    #     moduleDirectory: .
    #     # testArguments: ./HelloWorld/...
    #     testArguments: ./...
    #     omitUntestedPackages: true
    #     omitPie: true