name: Tests

on: 
  push:
    branches:
    - 'main'
    - 'develop'


jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.21.6'

    - name: Install dependencies
      run: go mod download

    - name: Run tests
      run: go test ./...

    - name: Test
      uses: robherley/go-test-action@v0.1.0
